/*! URI.js v1.7.1 http://medialize.github.com/URI.js/ */
/* build contains: URI.js */
(function(g){function j(a){return a.replace(/([.*+?^=!:${}()|[\]\/\\])/g,"\\$1")}function l(a){return"[object Array]"===String(Object.prototype.toString.call(a))}function p(a){return encodeURIComponent(a).replace(/[!'()*]/g,escape)}var d="undefined"!==typeof module&&module.exports,o=d?require("./punycode"):window.punycode,q=d?require("./IPv6"):window.IPv6,n=d?require("./SecondLevelDomains"):window.SecondLevelDomains,e=function(a,b){if(!(this instanceof e))return new e(a,b);a===g&&(a=location.href+
"");this.href(a);return b!==g?this.absoluteTo(b):this},d=e.prototype;e.idn_expression=/[^a-z0-9\.-]/i;e.punycode_expression=/(xn--)/i;e.ip4_expression=/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/;e.ip6_expression=/^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?\s*$/;
e.find_uri_expression=/\b((?:[a-z][\w-]+:(?:\/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}\/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))/ig;e.defaultPorts={http:"80",https:"443",ftp:"21"};e.invalid_hostname_characters=/[^a-zA-Z0-9\.-]/;e.encode=p;e.decode=decodeURIComponent;e.iso8859=function(){e.encode=escape;e.decode=unescape};e.unicode=function(){e.encode=p;e.decode=decodeURIComponent};
e.characters={pathname:{encode:{expression:/%(24|26|2B|2C|3B|3D|3A|40)/ig,map:{"%24":"$","%26":"&","%2B":"+","%2C":",","%3B":";","%3D":"=","%3A":":","%40":"@"}},decode:{expression:/[\/\?#]/g,map:{"/":"%2F","?":"%3F","#":"%23"}}},reserved:{encode:{expression:/%(21|23|24|26|27|28|29|2A|2B|2C|2F|3A|3B|3D|3F|40|5B|5D)/ig,map:{"%3A":":","%2F":"/","%3F":"?","%23":"#","%5B":"[","%5D":"]","%40":"@","%21":"!","%24":"$","%26":"&","%27":"'","%28":"(","%29":")","%2A":"*","%2B":"+","%2C":",","%3B":";","%3D":"="}}}};
e.encodeQuery=function(a){return e.encode(a+"").replace(/%20/g,"+")};e.decodeQuery=function(a){return e.decode((a+"").replace(/\+/g,"%20"))};e.recodePath=function(a){for(var a=(a+"").split("/"),b=0,c=a.length;b<c;b++)a[b]=e.encodePathSegment(e.decode(a[b]));return a.join("/")};e.decodePath=function(a){for(var a=(a+"").split("/"),b=0,c=a.length;b<c;b++)a[b]=e.decodePathSegment(a[b]);return a.join("/")};var i={encode:"encode",decode:"decode"},h,m=function(a,b){return function(c){return e[b](c+"").replace(e.characters[a][b].expression,
function(c){return e.characters[a][b].map[c]})}};for(h in i)e[h+"PathSegment"]=m("pathname",i[h]);e.encodeReserved=m("reserved","encode");e.parse=function(a){var b,c={};b=a.indexOf("#");-1<b&&(c.fragment=a.substring(b+1)||null,a=a.substring(0,b));b=a.indexOf("?");-1<b&&(c.query=a.substring(b+1)||null,a=a.substring(0,b));"//"===a.substring(0,2)?(c.protocol="",a=a.substring(2),a=e.parseAuthority(a,c)):(b=a.indexOf(":"),-1<b&&(c.protocol=a.substring(0,b),"//"===a.substring(b+1,b+3)?(a=a.substring(b+
3),a=e.parseAuthority(a,c)):(a=a.substring(b+1),c.urn=!0)));c.path=a;return c};e.parseHost=function(a,b){var c=a.indexOf("/"),f;-1===c&&(c=a.length);"["===a[0]?(f=a.indexOf("]"),b.hostname=a.substring(1,f)||null,b.port=a.substring(f+2,c)||null):a.indexOf(":")!==a.lastIndexOf(":")?(b.hostname=a.substring(0,c)||null,b.port=null):(f=a.substring(0,c).split(":"),b.hostname=f[0]||null,b.port=f[1]||null);b.hostname&&"/"!==a.substring(c)[0]&&(c++,a="/"+a);return a.substring(c)||"/"};e.parseAuthority=function(a,
b){a=e.parseUserinfo(a,b);return e.parseHost(a,b)};e.parseUserinfo=function(a,b){var c=a.indexOf("@"),f=a.indexOf("/");-1<c&&(-1===f||c<f)?(f=a.substring(0,c).split(":"),b.username=f[0]?e.decode(f[0]):null,b.password=f[1]?e.decode(f[1]):null,a=a.substring(c+1)):(b.username=null,b.password=null);return a};e.parseQuery=function(a){if(!a)return{};a=a.replace(/&+/g,"&").replace(/^\?*&*|&+$/g,"");if(!a)return{};for(var b={},a=a.split("&"),c=a.length,f=0;f<c;f++){var k=a[f].split("="),d=e.decodeQuery(k.shift()),
k=k.length?e.decodeQuery(k.join("=")):null;b[d]?("string"===typeof b[d]&&(b[d]=[b[d]]),b[d].push(k)):b[d]=k}return b};e.build=function(a){var b="";a.protocol&&(b+=a.protocol+":");if(!a.urn&&(b||a.hostname))b+="//";b+=e.buildAuthority(a)||"";"string"===typeof a.path&&("/"!==a.path[0]&&"string"===typeof a.hostname&&(b+="/"),b+=a.path);"string"===typeof a.query&&(b+="?"+a.query);"string"===typeof a.fragment&&(b+="#"+a.fragment);return b};e.buildHost=function(a){var b="";if(a.hostname)e.ip6_expression.test(a.hostname)?
b=a.port?b+("["+a.hostname+"]:"+a.port):b+a.hostname:(b+=a.hostname,a.port&&(b+=":"+a.port));else return"";return b};e.buildAuthority=function(a){return e.buildUserinfo(a)+e.buildHost(a)};e.buildUserinfo=function(a){var b="";a.username&&(b+=e.encode(a.username),a.password&&(b+=":"+e.encode(a.password)),b+="@");return b};e.buildQuery=function(a,b){var c="",f;for(f in a)if(Object.hasOwnProperty.call(a,f)&&f)if(l(a[f]))for(var k={},d=0,h=a[f].length;d<h;d++)a[f][d]!==g&&k[a[f][d]+""]===g&&(c+="&"+e.buildQueryParameter(f,
a[f][d]),!0!==b&&(k[a[f][d]+""]=!0));else a[f]!==g&&(c+="&"+e.buildQueryParameter(f,a[f]));return c.substring(1)};e.buildQueryParameter=function(a,b){return e.encodeQuery(a)+(null!==b?"="+e.encodeQuery(b):"")};e.addQuery=function(a,b,c){if("object"===typeof b)for(var f in b)Object.prototype.hasOwnProperty.call(b,f)&&e.addQuery(a,f,b[f]);else if("string"===typeof b)a[b]===g?a[b]=c:("string"===typeof a[b]&&(a[b]=[a[b]]),l(c)||(c=[c]),a[b]=a[b].concat(c));else throw new TypeError("URI.addQuery() accepts an object, string as the name parameter");
};e.removeQuery=function(a,b,c){if(l(b))for(var c=0,f=b.length;c<f;c++)a[b[c]]=g;else if("object"===typeof b)for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&e.removeQuery(a,f,b[f]);else if("string"===typeof b)if(c!==g)if(a[b]===c)a[b]=g;else{if(l(a[b])){var f=a[b],k={},d,h;if(l(c)){d=0;for(h=c.length;d<h;d++)k[c[d]]=!0}else k[c]=!0;d=0;for(h=f.length;d<h;d++)k[f[d]]!==g&&(f.splice(d,1),h--,d--);a[b]=f}}else a[b]=g;else throw new TypeError("URI.addQuery() accepts an object, string as the first parameter");
};e.commonPath=function(a,b){var c=Math.min(a.length,b.length),f;for(f=0;f<c;f++)if(a[f]!==b[f]){f--;break}if(1>f)return a[0]===b[0]&&"/"===a[0]?"/":"";"/"!==a[f]&&(f=a.substring(0,f).lastIndexOf("/"));return a.substring(0,f+1)};e.withinString=function(a,b){return a.replace(e.find_uri_expression,b)};e.ensureValidHostname=function(a){if(a.match(e.invalid_hostname_characters)){if(!o)throw new TypeError("Hostname '"+a+"' contains characters other than [A-Z0-9.-] and Punycode.js is not available");if(o.toASCII(a).match(e.invalid_hostname_characters))throw new TypeError("Hostname '"+
a+"' contains characters other than [A-Z0-9.-]");}};d.build=function(a){if(!0===a)this._deferred_build=!0;else if(a===g||this._deferred_build)this._string=e.build(this._parts),this._deferred_build=!1;return this};d.clone=function(){return new e(this)};d.toString=function(){return this.build(!1)._string};d.valueOf=function(){return this.toString()};i={protocol:"protocol",username:"username",password:"password",hostname:"hostname",port:"port"};m=function(a){return function(b,c){if(b===g)return this._parts[a]||
"";this._parts[a]=b;this.build(!c);return this}};for(h in i)d[h]=m(i[h]);i={query:"?",fragment:"#"};m=function(a,b){return function(c,f){if(c===g)return this._parts[a]||"";null!==c&&(c+="",c[0]===b&&(c=c.substring(1)));this._parts[a]=c;this.build(!f);return this}};for(h in i)d[h]=m(h,i[h]);i={search:["?","query"],hash:["#","fragment"]};m=function(a,b){return function(c,f){var e=this[a](c,f);return"string"===typeof e&&e.length?b+e:e}};for(h in i)d[h]=m(i[h][1],i[h][0]);d.pathname=function(a,b){if(a===
g||!0===a){var c=this._parts.path||(this._parts.urn?"":"/");return a?e.decodePath(c):c}this._parts.path=a?e.recodePath(a):"/";this.build(!b);return this};d.path=d.pathname;d.href=function(a,b){if(a===g)return this.toString();this._string="";this._parts={protocol:null,username:null,password:null,hostname:null,urn:null,port:null,path:null,query:null,fragment:null};var c=a instanceof e,f="object"===typeof a&&(a.hostname||a.path),d;if("string"===typeof a)this._parts=e.parse(a);else if(c||f)for(d in c=
c?a._parts:a,c)Object.hasOwnProperty.call(this._parts,d)&&(this._parts[d]=c[d]);else throw new TypeError("invalid input");this.build(!b);return this};d.is=function(a){var b=!1,c=!1,f=!1,d=!1,g=!1,h=!1,i=!1,j=!this._parts.urn;this._parts.hostname&&(j=!1,c=e.ip4_expression.test(this._parts.hostname),f=e.ip6_expression.test(this._parts.hostname),b=c||f,g=(d=!b)&&n&&n.has(this._parts.hostname),h=d&&e.idn_expression.test(this._parts.hostname),i=d&&e.punycode_expression.test(this._parts.hostname));switch(a.toLowerCase()){case "relative":return j;
case "absolute":return!j;case "domain":case "name":return d;case "sld":return g;case "ip":return b;case "ip4":case "ipv4":case "inet4":return c;case "ip6":case "ipv6":case "inet6":return f;case "idn":return h;case "url":return!this._parts.urn;case "urn":return!!this._parts.urn;case "punycode":return i}return null};var s=d.protocol,t=d.port,u=d.hostname;d.protocol=function(a,b){if(a!==g&&a&&(a=a.replace(/:(\/\/)?$/,""),a.match(/[^a-zA-z0-9\.+-]/)))throw new TypeError("Protocol '"+a+"' contains characters other than [A-Z0-9.+-]");
return s.call(this,a,b)};d.scheme=d.protocol;d.port=function(a,b){if(this._parts.urn)return a===g?"":this;if(a!==g&&(0===a&&(a=null),a&&(a+="",":"===a[0]&&(a=a.substring(1)),a.match(/[^0-9]/))))throw new TypeError("Port '"+a+"' contains characters other than [0-9]");return t.call(this,a,b)};d.hostname=function(a,b){if(this._parts.urn)return a===g?"":this;if(a!==g){var c={};e.parseHost(a,c);a=c.hostname}return u.call(this,a,b)};d.host=function(a,b){if(this._parts.urn)return a===g?"":this;if(a===g)return this._parts.hostname?
e.buildHost(this._parts):"";e.parseHost(a,this._parts);this.build(!b);return this};d.authority=function(a,b){if(this._parts.urn)return a===g?"":this;if(a===g)return this._parts.hostname?e.buildAuthority(this._parts):"";e.parseAuthority(a,this._parts);this.build(!b);return this};d.userinfo=function(a,b){if(this._parts.urn)return a===g?"":this;if(a===g){if(!this._parts.username)return"";var c=e.buildUserinfo(this._parts);return c.substring(0,c.length-1)}"@"!==a[a.length-1]&&(a+="@");e.parseUserinfo(a,
this._parts);this.build(!b);return this};d.subdomain=function(a,b){if(this._parts.urn)return a===g?"":this;if(a===g){if(!this._parts.hostname||this.is("IP"))return"";var c=this._parts.hostname.length-this.domain().length-1;return this._parts.hostname.substring(0,c)||""}c=this._parts.hostname.length-this.domain().length;c=this._parts.hostname.substring(0,c);c=RegExp("^"+j(c));a&&"."!==a[a.length-1]&&(a+=".");a&&e.ensureValidHostname(a);this._parts.hostname=this._parts.hostname.replace(c,a);this.build(!b);
return this};d.domain=function(a,b){if(this._parts.urn)return a===g?"":this;"boolean"===typeof a&&(b=a,a=g);if(a===g){if(!this._parts.hostname||this.is("IP"))return"";var c=this._parts.hostname.match(/\./g);if(c&&2>c.length)return this._parts.hostname;c=this._parts.hostname.length-this.tld(b).length-1;c=this._parts.hostname.lastIndexOf(".",c-1)+1;return this._parts.hostname.substring(c)||""}if(!a)throw new TypeError("cannot set domain empty");e.ensureValidHostname(a);!this._parts.hostname||this.is("IP")?
this._parts.hostname=a:(c=RegExp(j(this.domain())+"$"),this._parts.hostname=this._parts.hostname.replace(c,a));this.build(!b);return this};d.tld=function(a,b){if(this._parts.urn)return a===g?"":this;"boolean"===typeof a&&(b=a,a=g);if(a===g){if(!this._parts.hostname||this.is("IP"))return"";var c=this._parts.hostname.lastIndexOf("."),c=this._parts.hostname.substring(c+1);return!0!==b&&n&&n.list[c.toLowerCase()]?n.get(this._parts.hostname)||c:c}if(a)if(a.match(/[^a-zA-Z0-9-]/))if(n&&n.is(a))c=RegExp(j(this.tld())+
"$"),this._parts.hostname=this._parts.hostname.replace(c,a);else throw new TypeError("TLD '"+a+"' contains characters other than [A-Z0-9]");else{if(!this._parts.hostname||this.is("IP"))throw new ReferenceError("cannot set TLD on non-domain host");c=RegExp(j(this.tld())+"$");this._parts.hostname=this._parts.hostname.replace(c,a)}else throw new TypeError("cannot set TLD empty");this.build(!b);return this};d.directory=function(a,b){if(this._parts.urn)return a===g?"":this;if(a===g||!0===a){if(!this._parts.path&&
!this._parts.hostname)return"";if("/"===this._parts.path)return"/";var c=this._parts.path.length-this.filename().length-1,c=this._parts.path.substring(0,c)||(this._parts.hostname?"/":"");return a?e.decodePath(c):c}c=this._parts.path.length-this.filename().length;c=this._parts.path.substring(0,c);c=RegExp("^"+j(c));this.is("relative")||(a||(a="/"),"/"!==a[0]&&(a="/"+a));a&&"/"!==a[a.length-1]&&(a+="/");a=e.recodePath(a);this._parts.path=this._parts.path.replace(c,a);this.build(!b);return this};d.filename=
function(a,b){if(this._parts.urn)return a===g?"":this;if(a===g||!0===a){if(!this._parts.path||"/"===this._parts.path)return"";var c=this._parts.path.lastIndexOf("/"),c=this._parts.path.substring(c+1);return a?e.decodePathSegment(c):c}c=!1;"/"===a[0]&&(a=a.substring(1));a.match(/\.?\//)&&(c=!0);var f=RegExp(j(this.filename())+"$"),a=e.recodePath(a);this._parts.path=this._parts.path.replace(f,a);c?this.normalizePath(b):this.build(!b);return this};d.suffix=function(a,b){if(this._parts.urn)return a===
g?"":this;if(a===g||!0===a){if(!this._parts.path||"/"===this._parts.path)return"";var c=this.filename(),f=c.lastIndexOf(".");if(-1===f)return"";c=c.substring(f+1);c=/^[a-z0-9%]+$/i.test(c)?c:"";return a?e.decodePathSegment(c):c}"."===a[0]&&(a=a.substring(1));if(c=this.suffix())f=a?RegExp(j(c)+"$"):RegExp(j("."+c)+"$");else{if(!a)return this;this._parts.path+="."+e.recodePath(a)}f&&(a=e.recodePath(a),this._parts.path=this._parts.path.replace(f,a));this.build(!b);return this};d.segment=function(a,b,
c){var e=this._parts.urn?":":"/",d=this.path(),r="/"===d.substring(0,1),d=d.split(e);"number"!==typeof a&&(c=b,b=a,a=g);if(a!==g&&"number"!==typeof a)throw Error("Bad segment '"+a+"', must be 0-based integer");r&&d.shift();0>a&&(a=Math.max(d.length+a,0));if(b===g)return a===g?d:d[a];if(null===a||d[a]===g)if(l(b))d=b;else{if(b||"string"===typeof b&&b.length)""===d[d.length-1]?d[d.length-1]=b:d.push(b)}else b||"string"===typeof b&&b.length?d[a]=b:d.splice(a,1);r&&d.unshift("");return this.path(d.join(e),
c)};var v=d.query;d.query=function(a,b){return!0===a?e.parseQuery(this._parts.query):a!==g&&"string"!==typeof a?(this._parts.query=e.buildQuery(a),this.build(!b),this):v.call(this,a,b)};d.addQuery=function(a,b,c){var f=e.parseQuery(this._parts.query);e.addQuery(f,a,b);this._parts.query=e.buildQuery(f);"string"!==typeof a&&(c=b);this.build(!c);return this};d.removeQuery=function(a,b,c){var f=e.parseQuery(this._parts.query);e.removeQuery(f,a,b);this._parts.query=e.buildQuery(f);"string"!==typeof a&&
(c=b);this.build(!c);return this};d.addSearch=d.addQuery;d.removeSearch=d.removeQuery;d.normalize=function(){return this._parts.urn?this.normalizeProtocol(!1).normalizeQuery(!1).normalizeFragment(!1).build():this.normalizeProtocol(!1).normalizeHostname(!1).normalizePort(!1).normalizePath(!1).normalizeQuery(!1).normalizeFragment(!1).build()};d.normalizeProtocol=function(a){"string"===typeof this._parts.protocol&&(this._parts.protocol=this._parts.protocol.toLowerCase(),this.build(!a));return this};
d.normalizeHostname=function(a){this._parts.hostname&&(this.is("IDN")&&o?this._parts.hostname=o.toASCII(this._parts.hostname):this.is("IPv6")&&q&&(this._parts.hostname=q.best(this._parts.hostname)),this._parts.hostname=this._parts.hostname.toLowerCase(),this.build(!a));return this};d.normalizePort=function(a){"string"===typeof this._parts.protocol&&this._parts.port===e.defaultPorts[this._parts.protocol]&&(this._parts.port=null,this.build(!a));return this};d.normalizePath=function(a){if(this._parts.urn||
!this._parts.path||"/"===this._parts.path)return this;var b,c,f=this._parts.path,d,g;"/"!==f[0]&&("."===f[0]&&(c=f.substring(0,f.indexOf("/"))),b=!0,f="/"+f);for(f=f.replace(/(\/(\.\/)+)|\/{2,}/g,"/");;){d=f.indexOf("/../");if(-1===d)break;else if(0===d){f=f.substring(3);break}g=f.substring(0,d).lastIndexOf("/");-1===g&&(g=d);f=f.substring(0,g)+f.substring(d+3)}b&&this.is("relative")&&(f=c?c+f:f.substring(1));f=e.recodePath(f);this._parts.path=f;this.build(!a);return this};d.normalizePathname=d.normalizePath;
d.normalizeQuery=function(a){"string"===typeof this._parts.query&&(this._parts.query.length?this.query(e.parseQuery(this._parts.query)):this._parts.query=null,this.build(!a));return this};d.normalizeFragment=function(a){this._parts.fragment||(this._parts.fragment=null,this.build(!a));return this};d.normalizeSearch=d.normalizeQuery;d.normalizeHash=d.normalizeFragment;d.iso8859=function(){var a=e.encode,b=e.decode;e.encode=escape;e.decode=decodeURIComponent;this.normalize();e.encode=a;e.decode=b;return this};
d.unicode=function(){var a=e.encode,b=e.decode;e.encode=p;e.decode=unescape;this.normalize();e.encode=a;e.decode=b;return this};d.readable=function(){var a=this.clone();a.username("").password("").normalize();var b="";a._parts.protocol&&(b+=a._parts.protocol+"://");a._parts.hostname&&(a.is("punycode")&&o?(b+=o.toUnicode(a._parts.hostname),a._parts.port&&(b+=":"+a._parts.port)):b+=a.host());a._parts.hostname&&(a._parts.path&&"/"!==a._parts.path[0])&&(b+="/");b+=a.path(!0);if(a._parts.query){for(var c=
"",f=0,d=a._parts.query.split("&"),h=d.length;f<h;f++){var i=(d[f]||"").split("="),c=c+("&"+e.decodeQuery(i[0]).replace(/&/g,"%26"));i[1]!==g&&(c+="="+e.decodeQuery(i[1]).replace(/&/g,"%26"))}b+="?"+c.substring(1)}return b+=a.hash()};d.absoluteTo=function(a){var b=this.clone(),c=["protocol","username","password","hostname","port"];if(this._parts.urn)throw Error("URNs do not have any generally defined hierachical components");if(this._parts.hostname)return b;a instanceof e||(a=new e(a));for(var f=
0,d;d=c[f];f++)b._parts[d]=a._parts[d];"/"!==b.path()[0]&&(a=a.directory(),b._parts.path=(a?a+"/":"")+b._parts.path,b.normalizePath());b.build();return b};d.relativeTo=function(a){var b=this.clone(),c=["protocol","username","password","hostname","port"],f;if(this._parts.urn)throw Error("URNs do not have any generally defined hierachical components");a instanceof e||(a=new e(a));if("/"!==this.path()[0]||"/"!==a.path()[0])throw Error("Cannot calculate common path from non-relative URLs");f=e.commonPath(b.path(),
a.path());for(var a=a.directory(),d=0,g;g=c[d];d++)b._parts[g]=null;if(!f||"/"===f)return b;if(a+"/"===f)b._parts.path="./"+b.filename();else{c="../";f=RegExp("^"+j(f));for(a=a.replace(f,"/").match(/\//g).length-1;a--;)c+="../";b._parts.path=b._parts.path.replace(f,c)}b.build();return b};d.equals=function(a){var b=this.clone(),c=new e(a),f={},d={},a={},g;b.normalize();c.normalize();if(b.toString()===c.toString())return!0;f=b.query();d=c.query();b.query("");c.query("");if(b.toString()!==c.toString()||
f.length!==d.length)return!1;f=e.parseQuery(f);d=e.parseQuery(d);for(g in f)if(Object.prototype.hasOwnProperty.call(f,g)){if(l(f[g])){if(!l(d[g])||f[g].length!==d[g].length)return!1;f[g].sort();d[g].sort();b=0;for(c=f[g].length;b<c;b++)if(f[g][b]!==d[g][b])return!1}else if(f[g]!==d[g])return!1;a[g]=!0}for(g in d)if(Object.prototype.hasOwnProperty.call(d,g)&&!a[g])return!1;return!0};"undefined"!==typeof module&&module.exports?module.exports=e:window.URI=e})();
